name: Build and Deploy to Alibaba Cloud ECS

on:
  push:
    branches:
      - main # 在推送到 main 分支时触发部署

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Vue project
        run: npm run build

      - name: Deploy to Aliyun ECS
        env:
          HOST: ${{ secrets.ALIYUN_HOST }}
          USERNAME: ${{ secrets.ALIYUN_USERNAME }}
          PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
          REMOTE_DIR: ${{ secrets.ALIYUN_REMOTE_DIR }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p "$PASSWORD" scp -o StrictHostKeyChecking=no -r dist/* $USERNAME@$HOST:$REMOTE_DIR
