name: Deploy to Alibaba ECS

on:
  push:
    branches:
      - main # 选择你的部署分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-vue-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-vue-app:latest

      - name: Deploy to Alibaba ECS
        env:
          HOST: ${{ secrets.ALIYUN_HOST }}
          USERNAME: ${{ secrets.ALIYUN_USERNAME }}
          PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-vue-app:latest
            docker stop my-vue-app || true
            docker rm my-vue-app || true
            docker run -d --name my-vue-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-vue-app:latest
          EOF
