name: Build and Deploy to Alibaba Cloud ECS

on:
  push:
    branches:
      - main # 在推送到 main 分支时触发部署

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Vue project
        run: npm run build

      - name: Check SSH Setup
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ECS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa_vue_demo
          chmod 600 ~/.ssh/id_rsa_vue_demo

          # 显示 SSH 文件内容（不打印私钥本身，防止泄漏）
          ls -la ~/.ssh
          ssh-keygen -lf ~/.ssh/id_rsa_vue_demo  # 输出公钥指纹确认密钥格式无误

          # 测试 SSH 连接
          ssh -i ~/.ssh/id_rsa_vue_demo -o StrictHostKeyChecking=no root@139.196.154.182 echo "SSH connection test successful"

      - name: Deploy to ECS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ECS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa_vue_demo  # 使用自定义名称
          chmod 600 ~/.ssh/id_rsa_vue_demo  # 设置权限

          # 添加 ECS 主机到 known_hosts
          ssh-keyscan -H 139.196.154.182 >> ~/.ssh/known_hosts


          ssh -i ~/.ssh/id_rsa_vue_demo -o StrictHostKeyChecking=no root@139.196.154.182 echo "SSH connection test successful"

          # 使用 rsync 传输文件到 ECS，指定私钥文件
          rsync -avz -e "ssh -i ~/.ssh/id_rsa_vue_demo" --delete dist/ root@139.196.154.182:/var/www/html
