name: Build and Deploy to Alibaba Cloud ECS

on:
  push:
    branches:
      - main # 在推送到 main 分支时触发部署

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Vue project
        run: npm run build

      - name: Deploy to ECS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ECS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa_vue_demo
          chmod 600 ~/.ssh/id_rsa_vue_demo

          # 将 ECS 主机添加到 known_hosts 文件以避免 Host key verification 错误
          ssh-keyscan -H 139.196.154.182 >> ~/.ssh/known_hosts


          rsync -avz --delete dist/ root@139.196.154.182:/home/vue-demo
